

```{r}
library(gitterhub)
```

```{r}
gt <- gitterService()
```


```{r}
gitter <- list()
gitter$groupId <- "614a89a76da037398486382a"
groups <- gt$list_groups()
groups <- gt$list_groupsAsDataframe() 

gitter$rooms <- gt$list_roomsUnderAGroupAsDataFrame(groupId = gitter$groupId)

gitter$roomIds <- as.list(gitter$rooms$id) |>
  setNames(gitter$rooms$name)
gitter$room_name <- "110-1-r4ds/main"

saveRDS(gitter, file="class_gitter.Rds")
gitter$roomIds$`110-1-r4ds/main`
```

```{r}
.roomId = gitter$roomIds$`110-1-r4ds/main`
postClipboard2Gitterchat <- function(){
  assertthat::assert_that(
    exists(".roomId", envir=.GlobalEnv),
    msg=".roomId does not exist in Global environment"
  )
  clipr::read_clip() |>
    paste0(collapse="\n") |>
    gitterhub::postMessageToARoom(
      roomId = .roomId
    )
}
```

```{r}
messageId <- get_messageIdFromGitterMessageCopyLink()
threadMsg <- generate_threadMessageInfo(roomId = roomId, messageId = messageId)

sheet_write_threadMsgInfo(threadMsg = threadMsg,
  sheetname=sheetname,
  ss=gitter$googleSheets$ss)
```

```{r}
.startingSemester <- lubridate::ymd("2021-9-19")
 


```

```{r}
lubridate::dweeks(1)
```


```{r}
messageId
sheetname = "week4"
roomId <- gitter$roomIds$`110-1-r4ds/main`
```


```{r}
threadMsg <- gitterhub:::get_threadMessagesInRoomFromAMessage(
  roomId,
  messageId
)

```

```{r}
roomId <- gitter$roomIds$`110-1-r4ds/main`
messageId <- "615c59ac9d20982e4fa20d99"
threadMsg <- generate_threadMessageInfo(roomId = roomId, messageId = messageId)

browseURL(threadMsg$url)
```


```{r}
library(googlesheets4)
googlesheets4::gs4_create(
  name="110-1-r4ds-gitterMonitor"
) -> gitter$googleSheets$ss
```

```{r}
sheetname = "week4"

sheet_write_threadMsgInfo(threadMsg = threadMsg,
  sheetname="week4",
  ss=gitter$googleSheets$ss)


```

## Google sheets formula

```{r}
ss <- googlesheets4::as_sheets_id("https://docs.google.com/spreadsheets/d/1LSjsiUQ3WHoWa-2767y_fs3qSwS9GDnxQlF5Hq6VJ0c/edit#gid=1129935409")
sheetname = "week4"
newColLetter = "D"
dd <- googlesheets4::range_read(ss,
  sheet=sheetname,
  range = "C1:C1")
messageId <- "615c2c13a41fd20699c6eb73"
names(dd)[[1]] -> link
linkContent <- glue::glue("=HYPERLINK(\"{link}\",\"{messageId}\")")
googlesheets4::range_write(
  ss,
  data = as.data.frame(
    googlesheets4::gs4_formula(linkContent)
  ),
  sheet=sheetname,
  range="C1:C1",
  col_names = F
)
```

